"""Sanity checks for evals/realizability scorers.

The contract: a coverage profile built by laying down real reads should be
trivially explained by NNLS deconvolution (residual ~ 0), while a profile
that wasn't generated by reads at all should not.
"""
from __future__ import annotations

import numpy as np
import pytest

from evals.realizability import (
    high_freq_energy_fraction,
    max_slope_excess,
    nnls_deconvolve,
    score_window,
    survival_kernel,
    tv_excess,
    tv_ratio,
    unconstrained_deconvolve,
)


def _build_coverage_from_reads(
    n_pos: int, starts: np.ndarray, lengths: np.ndarray
) -> np.ndarray:
    cov = np.zeros(n_pos, dtype=np.float64)
    for s, L in zip(starts, lengths):
        e = min(s + int(L), n_pos)
        cov[s:e] += 1.0
    return cov


def test_survival_kernel_basic():
    K = survival_kernel(np.array([1, 1, 2, 3], dtype=np.int64))
    # P(L > 0) = 4/4, P(L > 1) = 2/4, P(L > 2) = 1/4
    assert K.shape == (3,)
    np.testing.assert_allclose(K, [1.0, 0.5, 0.25])


def test_unconstrained_recovers_starts_for_realizable_profile():
    rng = np.random.default_rng(0)
    n_pos = 800
    lengths = rng.integers(low=80, high=200, size=2000)
    starts = rng.integers(low=0, high=n_pos - 50, size=2000)
    cov = _build_coverage_from_reads(n_pos, starts, lengths)
    K = survival_kernel(lengths, max_len=int(lengths.max()))
    out = unconstrained_deconvolve(cov, K)
    # Inverse filter reconstructs the profile to machine epsilon.
    assert out.residual_l2 < 1e-6, f"residual {out.residual_l2:.3e}"
    # Interior negative mass is small but not zero: the kernel is the
    # *expected* survival function and reads' realized lengths fluctuate
    # around it, so the inverse filter introduces some compensating
    # negatives. We only require that the relative comparison
    # (realizable < unrealizable) be far apart, asserted in the next test.
    assert out.neg_mass_fraction < 0.15


def test_random_profile_has_higher_neg_mass_than_real():
    rng = np.random.default_rng(1)
    n_pos = 800
    lengths = rng.integers(low=80, high=200, size=2000)
    K = survival_kernel(lengths)
    starts = rng.integers(low=0, high=n_pos - 50, size=2000)
    cov_real = _build_coverage_from_reads(n_pos, starts, lengths)
    cov_rand = rng.gamma(shape=1.0, scale=1.0, size=n_pos)
    cov_rand *= cov_real.sum() / cov_rand.sum()
    real_neg = unconstrained_deconvolve(cov_real, K).neg_mass_fraction
    rand_neg = unconstrained_deconvolve(cov_rand, K).neg_mass_fraction
    assert rand_neg > real_neg + 0.1, f"real={real_neg:.3f}  rand={rand_neg:.3f}"


def test_nnls_legacy_path_still_runs():
    """Slow true-NNLS path should produce a small residual on a realizable
    profile. Kept as a regression test; not used by score_window by default."""
    rng = np.random.default_rng(7)
    n_pos = 200  # keep small to stay fast
    lengths = rng.integers(low=50, high=150, size=500)
    starts = rng.integers(low=0, high=n_pos - 50, size=500)
    cov = _build_coverage_from_reads(n_pos, starts, lengths)
    K = survival_kernel(lengths)
    out = nnls_deconvolve(cov, K, compute_neg_mass=False)
    assert out.residual_l2 < 0.05


def test_tv_ratio_within_bound_for_realizable_profile():
    rng = np.random.default_rng(2)
    lengths = rng.integers(low=80, high=200, size=2000)
    starts = rng.integers(low=0, high=700, size=2000)
    cov = _build_coverage_from_reads(800, starts, lengths)
    # Bound: tv_ratio ≤ 1 for any read-aggregation process. Realized value
    # is typically well below 1 when reads densely overlap (starts and ends
    # cancel at shared positions).
    r = tv_ratio(cov, lengths)
    assert r <= 1.0 + 1e-6, f"tv_ratio={r} violates the upper bound"
    assert tv_excess(cov, lengths) == 0.0


def test_tv_ratio_low_for_oversmooth_profile():
    rng = np.random.default_rng(2)
    lengths = rng.integers(low=80, high=200, size=2000)
    cov = np.full(800, 50.0)
    assert tv_ratio(cov, lengths) < 0.05


def test_tv_excess_strictly_positive_for_jagged_profile():
    rng = np.random.default_rng(3)
    lengths = rng.integers(low=80, high=200, size=1000)
    cov = np.tile([10.0, 0.0], 400)
    assert tv_ratio(cov, lengths) > 1.5
    assert tv_excess(cov, lengths) > 0.5
    assert max_slope_excess(cov, lengths) > 0.5  # legacy alias


def test_high_freq_energy_fraction_is_higher_for_jagged_profile():
    rng = np.random.default_rng(4)
    lengths = rng.integers(low=80, high=200, size=2000)
    starts = rng.integers(low=0, high=700, size=2000)
    smooth = _build_coverage_from_reads(800, starts, lengths)
    jagged = np.tile([10.0, 0.0], 400).astype(np.float64)
    assert high_freq_energy_fraction(jagged, 50.0) > high_freq_energy_fraction(smooth, 50.0)


def test_score_window_returns_realizability_scores():
    rng = np.random.default_rng(5)
    lengths = rng.integers(low=80, high=200, size=1500)
    starts = rng.integers(low=0, high=600, size=1500)
    cov = _build_coverage_from_reads(800, starts, lengths)
    out = score_window(cov, lengths)
    expected_keys = {"neg_mass_fraction", "deconv_residual", "tv_ratio",
                     "tv_excess", "hf_energy_fraction"}
    assert expected_keys.issubset(out.keys())
    assert out["neg_mass_fraction"] < 0.20
    assert out["tv_excess"] == 0.0


def test_score_window_empty_lengths_returns_nans():
    out = score_window(np.zeros(100), np.array([], dtype=np.int64))
    assert np.isnan(out["neg_mass_fraction"])
